### ISSUE TITLE
AttributeError: 'dlm' object has no attribute 'predictStatus'

### ISSUE THREAD

**Issue by raviy8408** [wwrechard/PyDLM#21]
Facing this issue when trying to make two points ahead prediction(for one point ahead prediction it works fine). Looked into the code, it appears that somehow continue prediction  module is not getting the first forecasts's AR component which is required for second forecast. I use following model:

# model_prediction
    data_pydlm = data.set_index('date', drop=True)
    myDLM_pred = dlm(data_pydlm.y)
    myDLM_pred = myDLM_pred + trend(degree=trend_degree, name='trend', w=trend_w)
    myDLM_pred = myDLM_pred + seasonality(12, name='12month', w=seasonality_w)
    myDLM_pred = myDLM_pred + autoReg(degree=ar_degree, data=prod_pydlm.y, name='ar', w = ar_w)

    myDLM_pred.fit()

Error:

print(myDLM_pred.predictN(N=2, date=myDLM_pred.n - 1))
  File "C:\Anaconda\Anaconda3\lib\site-packages\pydlm\dlm.py", line 379, in predictN
    (obs, var) = self.continuePredict(featureDict=featureDictOneDay)
  File "C:\Anaconda\Anaconda3\lib\site-packages\pydlm\dlm.py", line 328, in continuePredict
    return self._continuePredict(featureDict=featureDict)
  File "C:\Anaconda\Anaconda3\lib\site-packages\pydlm\func\_dlm.py", line 441, in _continuePredict
    extra = comp.d - len(self.predictStatus[2])
AttributeError: 'dlm' object has no attribute 'predictStatus'

I would appreciate any help with this

**Comment by raviy8408** [comment]
I could find out that the issue is for higher order AR. I face it for AR = 2

**Comment by wwrechard** [comment]
Hi Ravi,

Thanks for reaching out. This issue should have been fixed in the recent
update of the github version, could you give that a try? I will update the
pypi version later.

Thanks!

**Comment by raviy8408** [comment]
Thanks Sam!
I installed the latest build on github, the issue is resolved. 
I appreciate your work on this library.
Regards,
Ravi
