### ISSUE TITLE
Allow user to suppress warning on dynamic components

### ISSUE THREAD

**Issue by microprediction** [wwrechard/PyDLM#50]
Line 729 of dlm.py reads: 

   if len(self.builder.dynamicComponents) > 0:
                print('Remember to append the new features for the' +
                      ' dynamic components as well')

I'm going to suggest allowing suppression of this, as there isn't a way to add the data to 'main' and also dynamic at the same time - so this message will always be displayed, often in an inner loop.

**Comment by wwrechard** [comment]
with the new version release (0.1.1.13), users should be able to mute any unnecessary logs
