### ISSUE TITLE
How do I create a Time Varying Model using pydlm?

### ISSUE THREAD

**Issue by Samya98** [wwrechard/PyDLM#52]
I want to create a Time Varying Linear model like this:
![image](https://user-images.githubusercontent.com/58078956/111147453-88281a80-85b0-11eb-98d9-78c0a731f352.png)
How should I proceed with the same? You documentations lacks some notations, adding which would be really beneficial. But nice work. Its really useful in my research

**Comment by phaabe** [comment]
@Samya98 did you find documentation or a solution? Would you share it please?

**Comment by Samya98** [comment]
> @Samya98 did you find documentation or a solution? Would you share it please?

Hey. I read the document carefully and focused on the Dynamic Component. It turns out that all i needed was to use the code
`dlm(y) + trend(discount=1) + dynamic(X, discount=1)` to get the above model. I hope this helps. By default, dynamic takes one regressor, in my case X. If you want more, just add the same to the argument and supply the data.
