### ISSUE TITLE
where does regressor10 come from?

### ISSUE THREAD

**Issue by veridelisi** [wwrechard/PyDLM#66]
Hello
where does regressor10 come from?
thank you

**Comment by wwrechard** [comment]
Hi @veridelisi, are you asking about the example in the readme? The whole script and data is provided [here](https://github.com/wwrechard/pydlm/tree/master/examples/unemployment_insurance). For your specific question about `regressor10`, it was created by loading the data from the csv and the code can be found [here](https://github.com/wwrechard/pydlm/blob/master/examples/unemployment_insurance/main.py#L12-L29).

**Comment by veridelisi** [comment]
Hello
regressor10 is created in 67. row
regressor10 = dynamic(features=features, discount=1.0, name='regressor10', w=10)
what is the exactly regressor10?
thank you

**Comment by samuelwxy** [comment]
It is a regressor loading the data highlighted in my previous comment. Are you asking what is the data in that feature? That is the unemployment claim data. You can read more from the original google data post: https://www.unofficialgoogledatascience.com/2017/07/fitting-bayesian-structural-time-series.html

**Comment by wwrechard** [comment]
It is a regressor loading the data highlighted in my previous comment. Are you asking what is the data in that feature? That is the unemployment claim data. You can read more from the original google data post: https://www.unofficialgoogledatascience.com/2017/07/fitting-bayesian-structural-time-series.html
